config:
  global:
    resolve_timeout: 5m

  route:
    receiver: 'webhook-receiver'

  receivers:
    - name: 'webhook-receiver'
      webhook_configs:
        - url: 'https://39b513c68ffc.ngrok-free.app/webhook'

