image:
  repository: myapp
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000

replicaCount: 1

serviceAccount:
  create: false

ingress:
  enabled: false

autoscaling:
  enabled: false
