grafana:
  adminPassword: admin
  service:
    type: NodePort
    nodePort: 32000
  sidecar:
    datasources:
      enabled: true
    dashboards:
      enabled: true
  grafana.ini:
    paths:
      provisioning: /etc/grafana/provisioning
  env:
    GF_INSTALL_PLUGINS: "victoriametrics-logs-datasource"

prometheus:
  service:
    type: NodePort
    nodePort: 30900
  prometheusSpec:
    enableFeatures:
      - exemplar-storage  # helpful later for trace<->metric links

alertmanager:
  enabled: true
