deploymentMode: SingleBinary

loki:
  config: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    common:
      path_prefix: /var/loki
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: 2024-01-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    storage_config:
      filesystem:
        directory: /var/loki/chunks

    compactor:
      working_directory: /var/loki/compactor

    limits_config:
      retention_period: 168h
      allow_structured_metadata: true

    table_manager:
      retention_deletes_enabled: false

  # explicit schemaConfig to satisfy helm validate
  schemaConfig:
    configs:
      - from: 2024-01-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

  # helper keys
  storage:
    use_thanos_objstore: false
    bucketNames:
      chunks: loki-chunks
      index: loki-index
      ruler: loki-ruler

  commonConfig:
    replication_factor: 1

persistence:
  enabled: true
  storageClass: standard    # keep as your PV used 'standard' earlier
  accessModes:
    - ReadWriteOnce
  size: 10Gi

limits_config:
  retention_period: 168h
  allow_structured_metadata: true

