# promtail.values.victoria.yaml - replace/merge into your existing promtail values
config:
  clients:
    - url: http://victorialogs.observability.svc.cluster.local:9428/insert/loki/api/v1/push

  positions:
    filename: /data/positions.yaml

  server:
    http_listen_port: 9080

  scrape_configs:
    - job_name: kubernetes-pods
      pipeline_stages: []
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod

