config:
  server:
    http_listen_port: 3101
  clients:
    - url: http://loki:3100/loki/api/v1/push
  positions:
    filename: /run/promtail/positions.yaml
  snippets:
    pipelineStages:
      - cri: {}
      - labeldrop:
          - filename
      - timestamp:
          source: time
          format: RFC3339
daemonset:
  enabled: true
