tempo:
  receivers:
    otlp:
      protocols:
        grpc: {}   # 4317
        http: {}   # 4318
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
  server:
    http_listen_port: 3200
  metricsGenerator:
    enabled: false
persistence:
  enabled: true
  size: 10Gi

